name: flutter_look_around
description: A Flutter plugin that integrates MKLookaround for iOS, providing a seamless way to display panoramic street views using Apple's MapKit.
version: 0.0.1
license: BSD-3-Clause
repository: https://github.com/quonji/flutter_look_around
issue_tracker: https://github.com/quonji/flutter_look_around/issues

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  stream_transform: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: SwiftLookaroundPlugin